import java.io.*;
import jakarta.servlet.*;
import jakarta.servlet.annotation.*;
import jakarta.servlet.http.*;

/** Simple servlet for testing. Generates HTML instead of plain
 *  text as with the HelloWorld servlet.
 */

@WebServlet("/mysrv")
public class MyServlet extends HttpServlet {
  @Override
  public void doGet(HttpServletRequest request,
                    HttpServletResponse response)
      throws ServletException, IOException {
    response.setContentType("text/html");
    PrintWriter out = response.getWriter();
    out.println
      ("<!DOCTYPE html>\n" +
       "<html>\n" +
       "<head><title>A Dynamic Web Page</title></head>\n" +
       "<body bgcolor=\"#fdf5e6\">\n" +
       "<h1>A Dynamic Web Page</h1>\n" +
       "<p>A web page generated by a simple servlet</p>\n" +
       "</body></html>");
  }
}
